### ISSUE TITLE
(5) [Pivot table] Draggable

### ISSUE THREAD

**Issue by lucasjoao** [laboratoriobridge/bold#664]
# Draggable

Draggable is a container to the filter that can be "draggable" in the filter box (#658) of pivot table.

### **Visual example**

![image](https://user-images.githubusercontent.com/15273298/116892803-9ab0ee80-ac06-11eb-8237-f5e5b44ca43c.png)

From [figma](https://www.figma.com/file/TE9FUDtlgVQ4FWlAPtTagxQU/Bold-Design-System?node-id=9608%3A5789).

### **Attention**

Check if will be need use libs that aren't Bold dependencies: `react-dnd` and `react-window`.

**Comment by zDudaHang** [comment]
# Some important observations of this component
All of these behaviors happen because this component depends on a state called `selectedItems` of a parent component (which will come later) and doesn't have a state of its own to keep track of which items have been selected. That's why there is the `onFilterUpdate` method to update the selected items, making it possible to change the state of the parent component. Everything will be resolved with the arrival of the new components.

### When the user clicks on "All items", the list elements will not have their checkboxes checked
https://user-images.githubusercontent.com/25747989/120402879-83eedc00-c319-11eb-94e5-7b3c079a0032.mp4

### When the user clicks on an item, the checkbox is not checked 
https://user-images.githubusercontent.com/25747989/120402882-84877280-c319-11eb-8cec-d55bc1d94ae2.mp4
